version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bts
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bts.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - db
  nest-app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      JWT_SECRET: $2a$10$KKogmlfxOvj0kqznAxgCtu1fNTOV2D3vP9n.ydlyjeHJiR4fWY882
      DB_HOST: db
      DB_USER: postgres
      DB_PW: mysecretpassword
      DB_PORT: 5432
      ORIGINS: http://localhost:5173,http://localhost:5174,http://localhost:42467,https://dashboard.devhungops.website,http://localhost:3000
  ui:
    image: hung6876/bts-ui
    container_name: ui
    ports:
      - "5174:80"
    
volumes:
  db-data: