export const initTicketData = [
    {
        id: 5, 
        seat: '{"5"}', 
        foods: '{"key": "khoai tay chien"}',
        paymentMethod: 'momo',
        movieName: 'movieName',
        cinemaName: 'cinemaName',
        totalTicket: 150000,
        totalFood: 10000,
        movieImage: 'movieImage',
        code: 'code',
        createdAt: '2023-06-04 12:30:00',
        showtimeId: 'ny981sZk7s3sY8EbWSvtQz',
        userId: 'euQJtq9bgfPVvPdb2EoFXW',
    },
    {
        id: 6, 
        seat: '{"6"}', 
        foods: '{"key": "khoai tay chien, nuoc, bap"}',
        paymentMethod: 'momo',
        movieName: 'movieName',
        cinemaName: 'cinemaName',
        totalTicket: 150000,
        totalFood: 300000,
        movieImage: 'movieImage',
        code: 'code',
        createdAt: '2023-06-04 12:30:00',
        showtimeId: 'ny981sZk7s3sY8EbWSvtQz',
        userId: 'euQJtq9bgfPVvPdb2EoFXW',
    },
    {
        id: 7, 
        seat: '{"7"}', 
        foods: '{"key": "khoai tay chien, nuoc"}',
        paymentMethod: 'momo',
        movieName: 'movieName',
        cinemaName: 'cinemaName',
        totalTicket: 250000,
        totalFood: 150000,
        movieImage: 'movieImage',
        code: 'code',
        createdAt: '2023-06-04 12:30:00',
        showtimeId: 'ny981sZk7s3sY8EbWSvtQz',
        userId: 'euQJtq9bgfPVvPdb2EoFXW',
    },
  ];
  