name: Deploy to Azure VM

on:
  push:
    branches: [develop]
  
jobs:
      
  build: 
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm i
    - run: npm run build


  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Install SSH client
      run: sudo apt-get install -y ssh

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        port: ${{ secrets.AZURE_VM_SSH_PORT }}
        script: |
          cd booking-ticket-system-service
          git pull
          yarn build
          pm2 restart 0
